appVersion: 0.13.0
description: Fast and Lightweight Log/Data Forwarder for Linux, BSD and OSX
home: http://fluentbit.io
icon: http://fluentbit.io/assets/img/logo1-default.png
keywords:
- logging
- monitoring
- fluent
- fluentd
maintainers:
- email: Kevin.Fox@pnnl.gov
  name: kfox1111
- email: eduardo@treasure-data.com
  name: edsiper
name: fluent-bit
sources:
- http://fluentbit.io
version: 0.6.0
