FROM alpine:3.7
ENV MAVEN_REPO https://maven.cloudant.com/repo/

ADD ./maven-mirror/mirror-it /usr/bin

RUN apk add --no-cache wget \
  && chmod +x /usr/bin/mirror-it \
  && mkdir -p /maven_repo

VOLUME ["/maven_repo"]

CMD ["/usr/bin/mirror-it"]
